<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../Hosts/ATS.Api/ATS.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- WebApplicationFactory<Program>: goi API that trong bo nho, khong can container. -->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

</Project>
