<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../Modules/Recruitment/ATS.Recruitment.Infrastructure/ATS.Recruitment.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/AiScreening/ATS.AiScreening.Infrastructure/ATS.AiScreening.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Identity/ATS.Identity.Infrastructure/ATS.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../../Hosts/ATS.Api/ATS.Api.csproj" />
  </ItemGroup>

</Project>
